# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '0204.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(659, 570)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(170, 10, 331, 461))
        self.widget.setStyleSheet("background-color: rgb(123, 123, 123);")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(90, 160, 151, 81))
        self.label.setStyleSheet("background-color: rgb(80, 80, 80);\n"
"font: 63 18pt \"American Typewriter\";\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(30, 20, 271, 121))
        self.widget_2.setStyleSheet("background-color: rgb(55, 55, 55);")
        self.widget_2.setObjectName("widget_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 251, 31))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 251, 61))
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(20, 320, 71, 31))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 260, 113, 21))
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setGeometry(QtCore.QRect(180, 260, 113, 21))
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(150, 260, 21, 16))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton1 = QtWidgets.QPushButton(self.widget)
        self.pushButton1.setGeometry(QtCore.QRect(30, 390, 61, 31))
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton2 = QtWidgets.QPushButton(self.widget)
        self.pushButton2.setGeometry(QtCore.QRect(110, 390, 61, 31))
        self.pushButton2.setObjectName("pushButton2")
        self.pushButton3 = QtWidgets.QPushButton(self.widget)
        self.pushButton3.setGeometry(QtCore.QRect(190, 390, 61, 31))
        self.pushButton3.setObjectName("pushButton3")
        self.pushButtonAdd = QtWidgets.QPushButton(self.widget)
        self.pushButtonAdd.setGeometry(QtCore.QRect(110, 320, 71, 31))
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.pushButtonEqual = QtWidgets.QPushButton(self.widget)
        self.pushButtonEqual.setGeometry(QtCore.QRect(190, 320, 113, 32))
        self.pushButtonEqual.setObjectName("pushButtonEqual")
        self.pushButton4 = QtWidgets.QPushButton(self.widget)
        self.pushButton4.setGeometry(QtCore.QRect(260, 390, 61, 31))
        self.pushButton4.setObjectName("pushButton4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "The Calculator"))
        self.pushButton.setText(_translate("Dialog", "AC"))
        self.label_2.setText(_translate("Dialog", "+"))
        self.pushButton1.setText(_translate("Dialog", "1"))
        self.pushButton2.setText(_translate("Dialog", "2"))
        self.pushButton3.setText(_translate("Dialog", "3"))
        self.pushButtonAdd.setText(_translate("Dialog", "+"))
        self.pushButtonEqual.setText(_translate("Dialog", "="))
        self.pushButton4.setText(_translate("Dialog", "4"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
